### ISSUE TITLE
Input dimension of nonlinear projector model for StyleGAN2

### ISSUE THREAD

**Issue by ElektrischesSchaf** [catlab-team/latentclr#4]
Hi,

Currently I'm using StyleGAN2 and extract the output from feature layer "conv1" as mentioned in the paper.
The dimension of the input layer in NonlinearProjector, according to  ```conf/size/stylegan2_nonliner.yaml```, is 512. But I got 8192 instead since the output size from 'conv1' is actually [batch, 512, 4, 4]. Is it because I set ```use_w``` to True or I should overwrite the dimension setting in ```stylegan2_nonliner.yaml```? 

Thank you

**Comment by okyksl** [comment]
Hi @ElektrischesSchaf,

In the paper, we have used the identity projector instead of a nonlinear projector. Note that the direction models that apply latent edits are separate from the projectors that operate on features. For working with nonlinear projectors, you can just set the `in_features` property of the projector to 8192 as follows, `projector.in_features=8192`.
